controller_list:
  - name: fake_left_ur3_controller
    joints:
      - robot_left_arm_shoulder_pan_joint
      - robot_left_arm_shoulder_lift_joint
      - robot_left_arm_elbow_joint
      - robot_left_arm_wrist_1_joint
      - robot_left_arm_wrist_2_joint
      - robot_left_arm_wrist_3_joint
  - name: fake_right_ur3_controller
    joints:
      - robot_right_arm_shoulder_pan_joint
      - robot_right_arm_shoulder_lift_joint
      - robot_right_arm_elbow_joint
      - robot_right_arm_wrist_1_joint
      - robot_right_arm_wrist_2_joint
      - robot_right_arm_wrist_3_joint