# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: left_ur3
  joint_model_group_pose: todo_no_pose_selected
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - robot_left_wheel_joint
    - robot_right_wheel_joint
    - robot_left_arm_shoulder_pan_joint
    - robot_left_arm_shoulder_lift_joint
    - robot_left_arm_elbow_joint
    - robot_left_arm_wrist_1_joint
    - robot_left_arm_wrist_2_joint
    - robot_left_arm_wrist_3_joint
    - robot_right_arm_shoulder_pan_joint
    - robot_right_arm_shoulder_lift_joint
    - robot_right_arm_elbow_joint
    - robot_right_arm_wrist_1_joint
    - robot_right_arm_wrist_2_joint
    - robot_right_arm_wrist_3_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: left_ur3_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robot_left_arm_shoulder_pan_joint
      - robot_left_arm_shoulder_lift_joint
      - robot_left_arm_elbow_joint
      - robot_left_arm_wrist_1_joint
      - robot_left_arm_wrist_2_joint
      - robot_left_arm_wrist_3_joint
  - name: right_ur3_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - robot_right_arm_shoulder_pan_joint
      - robot_right_arm_shoulder_lift_joint
      - robot_right_arm_elbow_joint
      - robot_right_arm_wrist_1_joint
      - robot_right_arm_wrist_2_joint
      - robot_right_arm_wrist_3_joint